#!/usr/bin/env bash
set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PKG_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DIABLO_WS="${DIABLO_WS:-/home/diablo/diablo_ws}"

source /opt/ros/foxy/setup.bash
if [ -f "${DIABLO_WS}/install/setup.bash" ]; then
  source "${DIABLO_WS}/install/setup.bash"
fi

export DIABLO_ROBOT_NAME="${DIABLO_ROBOT_NAME:-robot1}"
export ROS_DOMAIN_ID="${ROS_DOMAIN_ID:-51}"
export ROS_LOCALHOST_ONLY=0
export RMW_IMPLEMENTATION="${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}"
export FASTRTPS_DEFAULT_PROFILES_FILE="${FASTRTPS_DEFAULT_PROFILES_FILE:-${PKG_ROOT}/config/fastdds_udp_only.xml}"
export PYTHONPATH="${PKG_ROOT}:${PYTHONPATH:-}"
export DIABLO_ENABLE_POSTURE_TOOLS="${DIABLO_ENABLE_POSTURE_TOOLS:-true}"
export DIABLO_ENABLE_CLUSTER_TOOLS="${DIABLO_ENABLE_CLUSTER_TOOLS:-true}"
export DIABLO_CLUSTER_ROS_DOMAIN_IDS="${DIABLO_CLUSTER_ROS_DOMAIN_IDS:-51,52,53}"
export DIABLO_CLUSTER_ROBOT_NAMES="${DIABLO_CLUSTER_ROBOT_NAMES:-robot1,robot2,robot3}"
export DIABLO_CLUSTER_PRESTART="${DIABLO_CLUSTER_PRESTART:-true}"
export DIABLO_CLUSTER_CALL_RETRY_COUNT="${DIABLO_CLUSTER_CALL_RETRY_COUNT:-2}"
export DIABLO_CLUSTER_WORKER_RESTART_ATTEMPTS="${DIABLO_CLUSTER_WORKER_RESTART_ATTEMPTS:-2}"
export DIABLO_CLUSTER_WORKER_TIMEOUT_EXTRA_SEC="${DIABLO_CLUSTER_WORKER_TIMEOUT_EXTRA_SEC:-8}"
export DIABLO_CLUSTER_REQUIRE_SUBSCRIBER="${DIABLO_CLUSTER_REQUIRE_SUBSCRIBER:-true}"
export DIABLO_CLUSTER_REQUIRE_ALL_READY="${DIABLO_CLUSTER_REQUIRE_ALL_READY:-true}"
export DIABLO_CLUSTER_READY_RETRY_COUNT="${DIABLO_CLUSTER_READY_RETRY_COUNT:-3}"
export DIABLO_WAIT_FOR_SUBSCRIBER_MS="${DIABLO_WAIT_FOR_SUBSCRIBER_MS:-15000}"
export DIABLO_DISCOVERY_SETTLE_MS="${DIABLO_DISCOVERY_SETTLE_MS:-2000}"
exec python3 "${PKG_ROOT}/xiaozhi_robot_control/robot_mcp_server.py"
